/* TFLite Micro inference harness for the rusty-axon paper comparison.
 *
 * Loads the MNIST MLP exported by `python-tests/train_keras_mnist.py`
 * (architecture 784 -> 640 -> 320 -> 100 -> 10, ReLU/ReLU/ReLU/None) and
 * runs a fixed number of single-sample inferences. Two modes:
 *
 *   ./tflm_mnist                     -> 1 inference, prints argmax + RSS
 *   ./tflm_mnist bench <iters>       -> times <iters> inferences, prints
 *                                       average us/inference (used by the
 *                                       Burn/TFLM column of Table 1).
 *
 * The .tflite blob is embedded via the `mnist_mlp_tflite.h` header
 * generated by the Python script (portable `xxd -i` substitute).
 *
 * Build: see Makefile. The TFLM source tree is expected at
 * `tflite-micro/` next to this file (a git submodule).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(__linux__) || defined(__APPLE__)
#include <sys/resource.h>
#endif

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_log.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "mnist_mlp_tflite.h"  /* unsigned char mnist_mlp_tflite[]; */

/* Tensor arena. Sized for 784 -> 640 -> 320 -> 100 -> 10 with f32
 * activations: peak working set (largest pair of adjacent layer buffers
 * plus tensor metadata + op state) is ~16 KiB. 256 KiB leaves generous
 * headroom for op-state, scratch buffers, and alignment slack; we report
 * `arena_used_bytes()` so it can be tightened later for the binary-size
 * column once we know the true high-water mark. */
constexpr int kTensorArenaSize = 256 * 1024;
alignas(16) static uint8_t tensor_arena[kTensorArenaSize];

static void fill_fixed_input(float* dst, int n) {
  /* Match the deterministic LCG used by the rusty-axon and Burn benches
   * so all three frameworks chew on identical numerical workloads. */
  uint32_t state = 0x9E3779B9u;
  for (int i = 0; i < n; ++i) {
    state = state * 1664525u + 1013904223u;
    dst[i] = (float)(state >> 8) / (float)(1u << 24);
  }
}

static int argmax(const float* logits, int n) {
  int best = 0;
  float best_val = logits[0];
  for (int i = 1; i < n; ++i) {
    if (logits[i] > best_val) { best_val = logits[i]; best = i; }
  }
  return best;
}

#if defined(__linux__) || defined(__APPLE__)
static long peak_rss_kb(void) {
  struct rusage ru;
  if (getrusage(RUSAGE_SELF, &ru) != 0) return -1;
  /* Linux returns kilobytes, macOS returns bytes. */
#if defined(__APPLE__)
  return ru.ru_maxrss / 1024;
#else
  return ru.ru_maxrss;
#endif
}
#else
static long peak_rss_kb(void) { return -1; }
#endif

int main(int argc, char** argv) {
  int iters = 1;
  bool bench = false;
  if (argc >= 2 && strcmp(argv[1], "bench") == 0) {
    bench = true;
    iters = (argc >= 3) ? atoi(argv[2]) : 1000;
    if (iters <= 0) iters = 1000;
  }

  fprintf(stderr, "[diag] embedded model bytes: %zu\n",
          (size_t)sizeof(mnist_mlp_tflite));
  if (sizeof(mnist_mlp_tflite) < 16) {
    fprintf(stderr, "[diag] model blob too small -- header generation likely empty\n");
    return 1;
  }

  const tflite::Model* model = tflite::GetModel(mnist_mlp_tflite);
  fprintf(stderr, "[diag] model schema version: %d (runtime expects %d)\n",
          (int)model->version(), TFLITE_SCHEMA_VERSION);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    fprintf(stderr, "schema mismatch: model %d vs runtime %d\n",
            (int)model->version(), TFLITE_SCHEMA_VERSION);
    return 1;
  }

  /* Mutable op resolver. Bumped to 6 slots so the converter can pull in
   * Logistic / Add / etc. without tripping a silent registration failure.
   * We always register the four core ops we know an MLP needs; the rest
   * are belt-and-braces for converter quirks. */
  static tflite::MicroMutableOpResolver<6> resolver;
  resolver.AddFullyConnected();
  resolver.AddRelu();
  resolver.AddSoftmax();    /* harmless if absent; some converters add it */
  resolver.AddReshape();    /* leading Reshape from a Flatten layer        */
  resolver.AddLogistic();   /* belt-and-braces                              */
  resolver.AddAdd();        /* belt-and-braces (split bias)                 */

  tflite::MicroInterpreter interpreter(model, resolver, tensor_arena, kTensorArenaSize);
  TfLiteStatus alloc_status = interpreter.AllocateTensors();
  fprintf(stderr, "[diag] AllocateTensors status=%d  arena_used=%zu / %d bytes\n",
          (int)alloc_status, interpreter.arena_used_bytes(), kTensorArenaSize);
  if (alloc_status != kTfLiteOk) {
    fprintf(stderr, "AllocateTensors failed (status %d) -- bump kTensorArenaSize "
                    "or add the missing op above\n", (int)alloc_status);
    return 1;
  }

  fprintf(stderr, "[diag] inputs=%zu  outputs=%zu\n",
          interpreter.inputs_size(), interpreter.outputs_size());
  if (interpreter.inputs_size() == 0 || interpreter.outputs_size() == 0) {
    fprintf(stderr, "model exposes no inputs or outputs -- bad .tflite blob?\n");
    return 1;
  }

  TfLiteTensor* input = interpreter.input(0);
  TfLiteTensor* output = interpreter.output(0);
  if (input == nullptr || output == nullptr) {
    fprintf(stderr, "input/output tensor pointer is null (input=%p output=%p)\n",
            (void*)input, (void*)output);
    return 1;
  }
  fprintf(stderr, "[diag] input  type=%d bytes=%zu dims=%d",
          (int)input->type, (size_t)input->bytes,
          input->dims ? input->dims->size : -1);
  if (input->dims) {
    for (int i = 0; i < input->dims->size; ++i) fprintf(stderr, " %d", input->dims->data[i]);
  }
  fprintf(stderr, "\n[diag] output type=%d bytes=%zu dims=%d",
          (int)output->type, (size_t)output->bytes,
          output->dims ? output->dims->size : -1);
  if (output->dims) {
    for (int i = 0; i < output->dims->size; ++i) fprintf(stderr, " %d", output->dims->data[i]);
  }
  fprintf(stderr, "\n");

  /* Some TFLM builds return TfLiteTensor structs with a stripped `type`
   * and `dims` field for I/O tensors (header/lib ABI skew, or a slim
   * variant chosen at lib build time). When that happens we still trust
   * `bytes` and `data.f`: if input bytes == 784*4 and output bytes == 10*4
   * the model is the f32 MLP we shipped and Invoke will work. We only
   * hard-fail on types that genuinely mean "this is not f32" (Int8/UInt8,
   * which would have bytes == num_elements, an order of magnitude smaller). */
  const size_t expect_in_bytes  = 784 * sizeof(float);
  const size_t expect_out_bytes = 10  * sizeof(float);
  const bool bytes_match_f32 =
      input->bytes == expect_in_bytes && output->bytes == expect_out_bytes;

  if (input->type == kTfLiteInt8 || input->type == kTfLiteUInt8 ||
      output->type == kTfLiteInt8 || output->type == kTfLiteUInt8) {
    fprintf(stderr, "model has quantized IO (input=%d output=%d) -- re-export "
                    "the .tflite with no quantization (the train script's "
                    "TFLiteConverter already does this; check no extra opt flags).\n",
            (int)input->type, (int)output->type);
    return 1;
  }
  if (!bytes_match_f32) {
    fprintf(stderr, "byte counts don't match the expected 784->10 f32 MLP "
                    "(input=%zu expect=%zu, output=%zu expect=%zu).\n",
            (size_t)input->bytes, expect_in_bytes,
            (size_t)output->bytes, expect_out_bytes);
    return 1;
  }
  if (input->type != kTfLiteFloat32 || output->type != kTfLiteFloat32) {
    fprintf(stderr, "[warn] tensor type field reads %d/%d but byte counts "
                    "match f32 IO -- proceeding (likely TFLM header/lib ABI skew)\n",
            (int)input->type, (int)output->type);
  }
  const int input_len  = (int)(input->bytes  / sizeof(float));
  const int output_len = (int)(output->bytes / sizeof(float));

  fill_fixed_input(input->data.f, input_len);

  if (bench) {
    /* Warm up so the first-iteration cache miss doesn't dominate. */
    for (int i = 0; i < 8; ++i) (void)interpreter.Invoke();

    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (int i = 0; i < iters; ++i) {
      if (interpreter.Invoke() != kTfLiteOk) {
        fprintf(stderr, "Invoke failed at iter %d\n", i);
        return 1;
      }
    }
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double total_us =
        (double)(t1.tv_sec - t0.tv_sec) * 1e6 +
        (double)(t1.tv_nsec - t0.tv_nsec) / 1e3;
    printf("tflm_mnist bench iters=%d total_us=%.1f mean_us=%.3f\n",
           iters, total_us, total_us / iters);
    long rss = peak_rss_kb();
    if (rss >= 0) printf("peak_rss_kb=%ld\n", rss);
    return 0;
  }

  if (interpreter.Invoke() != kTfLiteOk) {
    fprintf(stderr, "Invoke failed\n");
    return 1;
  }
  fprintf(stderr, "[diag] logits:");
  for (int i = 0; i < output_len; ++i) fprintf(stderr, " %.4f", output->data.f[i]);
  fprintf(stderr, "\n");
  printf("argmax=%d\n", argmax(output->data.f, output_len));
  long rss = peak_rss_kb();
  if (rss >= 0) printf("peak_rss_kb=%ld\n", rss);
  return 0;
}
