/* TFLite Micro inference harness for the rusty-axon paper comparison.
 *
 * Loads the MNIST MLP exported by `python-tests/train_keras_mnist.py`
 * (architecture 784 -> 640 -> 320 -> 100 -> 10, ReLU/ReLU/ReLU/None) and
 * runs a fixed number of single-sample inferences. Two modes:
 *
 *   ./tflm_mnist                     -> 1 inference, prints argmax + RSS
 *   ./tflm_mnist bench <iters>       -> times <iters> inferences, prints
 *                                       average us/inference (used by the
 *                                       Burn/TFLM column of Table 1).
 *
 * The .tflite blob is embedded via the `mnist_mlp_tflite.h` header
 * generated by the Python script (portable `xxd -i` substitute).
 *
 * Build: see Makefile. The TFLM source tree is expected at
 * `tflite-micro/` next to this file (a git submodule).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#if defined(__linux__) || defined(__APPLE__)
#include <sys/resource.h>
#endif

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_log.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "mnist_mlp_tflite.h"  /* unsigned char mnist_mlp_tflite[]; */

/* Tensor arena. Sized for 784 -> 640 -> 320 -> 100 -> 10 with f32
 * activations: peak working set (largest pair of adjacent layer buffers
 * plus tensor metadata + op state) is ~16 KiB; 64 KiB is generous. */
constexpr int kTensorArenaSize = 64 * 1024;
alignas(16) static uint8_t tensor_arena[kTensorArenaSize];

static void fill_fixed_input(float* dst, int n) {
  /* Match the deterministic LCG used by the rusty-axon and Burn benches
   * so all three frameworks chew on identical numerical workloads. */
  uint32_t state = 0x9E3779B9u;
  for (int i = 0; i < n; ++i) {
    state = state * 1664525u + 1013904223u;
    dst[i] = (float)(state >> 8) / (float)(1u << 24);
  }
}

static int argmax(const float* logits, int n) {
  int best = 0;
  float best_val = logits[0];
  for (int i = 1; i < n; ++i) {
    if (logits[i] > best_val) { best_val = logits[i]; best = i; }
  }
  return best;
}

#if defined(__linux__) || defined(__APPLE__)
static long peak_rss_kb(void) {
  struct rusage ru;
  if (getrusage(RUSAGE_SELF, &ru) != 0) return -1;
  /* Linux returns kilobytes, macOS returns bytes. */
#if defined(__APPLE__)
  return ru.ru_maxrss / 1024;
#else
  return ru.ru_maxrss;
#endif
}
#else
static long peak_rss_kb(void) { return -1; }
#endif

int main(int argc, char** argv) {
  int iters = 1;
  bool bench = false;
  if (argc >= 2 && strcmp(argv[1], "bench") == 0) {
    bench = true;
    iters = (argc >= 3) ? atoi(argv[2]) : 1000;
    if (iters <= 0) iters = 1000;
  }

  const tflite::Model* model = tflite::GetModel(mnist_mlp_tflite);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    fprintf(stderr, "schema mismatch: model %d vs runtime %d\n",
            (int)model->version(), TFLITE_SCHEMA_VERSION);
    return 1;
  }

  /* Mutable op resolver: register only the ops the MLP actually uses
   * (FullyConnected, Relu, plus Softmax if the converter emitted one).
   * Keeping the op set tight is what makes TFLM's binary small. */
  static tflite::MicroMutableOpResolver<4> resolver;
  resolver.AddFullyConnected();
  resolver.AddRelu();
  resolver.AddSoftmax();   /* harmless if absent; some converters add it */
  resolver.AddReshape();   /* the converter sometimes emits a leading Reshape */

  tflite::MicroInterpreter interpreter(model, resolver, tensor_arena, kTensorArenaSize);
  TfLiteStatus alloc_status = interpreter.AllocateTensors();
  if (alloc_status != kTfLiteOk) {
    fprintf(stderr, "AllocateTensors failed (status %d)\n", (int)alloc_status);
    return 1;
  }

  TfLiteTensor* input = interpreter.input(0);
  TfLiteTensor* output = interpreter.output(0);
  if (input->type != kTfLiteFloat32 || output->type != kTfLiteFloat32) {
    fprintf(stderr, "expected f32 IO; got input=%d output=%d\n",
            (int)input->type, (int)output->type);
    return 1;
  }
  const int input_len = input->bytes / sizeof(float);
  const int output_len = output->bytes / sizeof(float);

  fill_fixed_input(input->data.f, input_len);

  if (bench) {
    /* Warm up so the first-iteration cache miss doesn't dominate. */
    for (int i = 0; i < 8; ++i) (void)interpreter.Invoke();

    struct timespec t0, t1;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (int i = 0; i < iters; ++i) {
      if (interpreter.Invoke() != kTfLiteOk) {
        fprintf(stderr, "Invoke failed at iter %d\n", i);
        return 1;
      }
    }
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double total_us =
        (double)(t1.tv_sec - t0.tv_sec) * 1e6 +
        (double)(t1.tv_nsec - t0.tv_nsec) / 1e3;
    printf("tflm_mnist bench iters=%d total_us=%.1f mean_us=%.3f\n",
           iters, total_us, total_us / iters);
    long rss = peak_rss_kb();
    if (rss >= 0) printf("peak_rss_kb=%ld\n", rss);
    return 0;
  }

  if (interpreter.Invoke() != kTfLiteOk) {
    fprintf(stderr, "Invoke failed\n");
    return 1;
  }
  printf("argmax=%d\n", argmax(output->data.f, output_len));
  long rss = peak_rss_kb();
  if (rss >= 0) printf("peak_rss_kb=%ld\n", rss);
  return 0;
}
