#!/usr/bin/env python3
"""Train an MNIST MLP in Keras and export to TFLite for the Phase K paper
comparison.

Architecture matches the Phase 8 criterion suite (`benches/common/mod.rs`),
`examples/mnist_classifier.rs`, and the Burn harness in
`scripts/compare_burn/`:

    784 -> 640 -> 320 -> 100 -> 10
    ReLU, ReLU, ReLU, None (logits; softmax fused into the loss)

Outputs (under `scripts/compare_tflite_micro/`):

* `mnist_mlp.tflite`         — float32 graph; consumed by the C harness
                                and embedded via `xxd -i`.
* `mnist_mlp.tflite.bytes`   — header `unsigned char[]` (xxd -i output)
                                so the C build doesn't depend on `xxd`
                                being available on Windows.
* `mnist_mlp_metadata.json`  — input/output shapes, dtype, train/test
                                accuracy, exact training config. Cited by
                                docs/COMPARISON.md so reviewers can verify
                                we trained an architecturally equivalent
                                model.

This script runs on the *host* (Windows or Linux) — TensorFlow is heavy
and cannot run on the Pi.

Usage:
    pip install tensorflow==2.16.* numpy
    python python-tests/train_keras_mnist.py
"""

from __future__ import annotations

import csv
import json
import os
import sys
from pathlib import Path

import numpy as np

try:
    import tensorflow as tf
except ImportError as exc:  # pragma: no cover - hint for the user
    sys.stderr.write(
        "TensorFlow not installed. Run:\n  pip install tensorflow==2.16.*\n"
    )
    raise SystemExit(1) from exc


ROOT = Path(__file__).resolve().parents[1]
MNIST_DIR = ROOT / "python-tests" / "mnist"
OUT_DIR = ROOT / "scripts" / "compare_tflite_micro"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# Pin everything so the .tflite hash is reproducible across runs.
SEED = 42
ARCH = (784, 640, 320, 100, 10)
EPOCHS = 25
BATCH_SIZE = 128
LEARNING_RATE = 1e-3


def load_csv(path: Path) -> tuple[np.ndarray, np.ndarray]:
    """Load `prepare_mnist.py`'s CSV format (label + 784 pixels in [0, 1])."""
    rows: list[list[float]] = []
    with path.open("r", newline="") as f:
        reader = csv.reader(f)
        for i, row in enumerate(reader):
            if i == 0 and row and row[0] == "label":
                continue
            rows.append([float(v) for v in row])
    arr = np.asarray(rows, dtype=np.float32)
    labels = arr[:, 0].astype(np.int64)
    pixels = arr[:, 1:]
    assert pixels.shape[1] == 784, f"expected 784 pixels, got {pixels.shape[1]}"
    return pixels, labels


def build_model() -> tf.keras.Model:
    tf.keras.utils.set_random_seed(SEED)
    model = tf.keras.Sequential(
        [
            tf.keras.layers.Input(shape=(ARCH[0],), name="input_pixels"),
            tf.keras.layers.Dense(ARCH[1], activation="relu", name="dense_1"),
            tf.keras.layers.Dense(ARCH[2], activation="relu", name="dense_2"),
            tf.keras.layers.Dense(ARCH[3], activation="relu", name="dense_3"),
            tf.keras.layers.Dense(ARCH[4], activation=None, name="logits"),
        ]
    )
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
        metrics=[tf.keras.metrics.SparseCategoricalAccuracy(name="acc")],
    )
    return model


def export_tflite(model: tf.keras.Model, dest: Path) -> bytes:
    """Convert to TFLite (float32, no quantization) and write to disk."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    # Float32 only — keep parity with rusty-axon's `min_inference` build.
    # If you also want an i8 variant for future Table 4 cells, add a
    # second conversion with `optimizations = [tf.lite.Optimize.DEFAULT]`
    # and a representative dataset.
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
    tflite_bytes = converter.convert()
    dest.write_bytes(tflite_bytes)
    return tflite_bytes


def write_xxd_header(blob: bytes, dest: Path, var_name: str) -> None:
    """Reproduce `xxd -i` output portably so the C build doesn't depend on
    xxd being installed (Windows toolchains usually lack it)."""
    lines = [
        f"// Auto-generated by python-tests/train_keras_mnist.py - do not edit.",
        f"// Mirrors `xxd -i {dest.with_suffix('.tflite').name}` output.",
        f"unsigned char {var_name}[] = {{",
    ]
    chunk = 12
    for i in range(0, len(blob), chunk):
        row = blob[i : i + chunk]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in row) + ",")
    lines.append("};")
    lines.append(f"unsigned int {var_name}_len = {len(blob)};")
    dest.write_text("\n".join(lines) + "\n", encoding="ascii")


def main() -> int:
    train_csv = MNIST_DIR / "mnist_train.csv"
    test_csv = MNIST_DIR / "mnist_test.csv"
    if not train_csv.exists() or not test_csv.exists():
        sys.stderr.write(
            f"MNIST CSVs not found under {MNIST_DIR}. "
            "Run python-tests/prepare_mnist.py first.\n"
        )
        return 2

    print(f"[1/4] Loading MNIST from {MNIST_DIR}")
    x_train, y_train = load_csv(train_csv)
    x_test, y_test = load_csv(test_csv)
    print(f"  train: {x_train.shape}, test: {x_test.shape}")

    print("[2/4] Building Keras model")
    model = build_model()
    model.summary()

    print(f"[3/4] Training {EPOCHS} epochs, batch={BATCH_SIZE}, lr={LEARNING_RATE}")
    history = model.fit(
        x_train,
        y_train,
        validation_data=(x_test, y_test),
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        verbose=2,
    )
    train_acc = float(history.history["acc"][-1])
    test_acc = float(history.history["val_acc"][-1])
    print(f"  final train acc = {train_acc:.4f}, test acc = {test_acc:.4f}")

    print("[4/4] Exporting TFLite + xxd header")
    tflite_path = OUT_DIR / "mnist_mlp.tflite"
    blob = export_tflite(model, tflite_path)
    print(f"  wrote {tflite_path} ({len(blob)} bytes)")

    header_path = OUT_DIR / "mnist_mlp_tflite.h"
    write_xxd_header(blob, header_path, "mnist_mlp_tflite")
    print(f"  wrote {header_path}")

    metadata = {
        "arch": list(ARCH),
        "activation_hidden": "relu",
        "activation_output": "none (logits)",
        "loss": "SparseCategoricalCrossentropy(from_logits=True)",
        "optimizer": "Adam",
        "learning_rate": LEARNING_RATE,
        "epochs": EPOCHS,
        "batch_size": BATCH_SIZE,
        "seed": SEED,
        "train_accuracy": train_acc,
        "test_accuracy": test_acc,
        "tflite_bytes": len(blob),
        "tensorflow_version": tf.__version__,
    }
    metadata_path = OUT_DIR / "mnist_mlp_metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(f"  wrote {metadata_path}")

    print()
    print("Done. Next: build the C harness in scripts/compare_tflite_micro/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
