#!/usr/bin/env python3
"""Render `binary_sizes.csv` to `docs/BINARY_SIZE.md`.

Phase 10 helper: consumes the CSV produced by `scripts/measure_binary_size.sh`
(or `.ps1`) and writes a Markdown table — one row per combo, with
human-readable byte counts.  No third-party deps.

Usage:
    python sizes_to_md.py <csv_path> <md_out>
"""

from __future__ import annotations

import csv
import datetime
import sys
from pathlib import Path


def fmt_bytes(raw: str) -> str:
    """Render an integer byte count as KiB/MiB; "—" if missing/empty."""
    if raw is None or raw == "":
        return "—"
    try:
        n = int(raw)
    except ValueError:
        return raw
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.1f} KiB"
    return f"{n / (1024 * 1024):.2f} MiB"


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    csv_path, md_out = Path(sys.argv[1]), Path(sys.argv[2])

    rows: list[dict[str, str]] = []
    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)

    md_out.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0)

    out: list[str] = []
    out.append("# Binary size matrix\n")
    out.append("\n")
    out.append(
        "Auto-generated by `scripts/measure_binary_size.sh` "
        "(or `.ps1`) + `scripts/sizes_to_md.py`. Do not edit by hand.\n"
    )
    out.append("\n")
    out.append(f"_Generated: {now.isoformat().replace('+00:00', 'Z')}_\n")
    out.append("\n")
    out.append(
        "Artifact in every row is `examples/min_inference` — the smallest "
        "realistic inference binary in the crate.  The `release-edge` profile "
        "(`Cargo.toml`) sets `lto = \"fat\"`, `codegen-units = 1`, "
        "`panic = \"abort\"`, `opt-level = \"z\"`, and `strip = \"symbols\"`, "
        "so rows that target it are stripped at link time without an extra "
        "post-step.\n"
    )
    out.append("\n")
    out.append("| ID | Profile | Features | Target | Strip | Size |\n")
    out.append("|---:|---------|----------|--------|:-----:|-----:|\n")
    for r in rows:
        size = fmt_bytes(r.get("bytes", ""))
        feats = (r.get("features", "") or "").strip('"')
        target = r.get("target", "") or ""
        out.append(
            f"| {r.get('id','')} | `{r.get('profile','')}` | `{feats}` | "
            f"{target} | {r.get('strip','')} | {size} |\n"
        )
    out.append("\n")
    out.append(
        "Empty `Size` cells indicate the combo could not be built in this "
        "environment (typically aarch64 rows when neither `cross` nor "
        "`cargo-zigbuild` is on PATH).\n"
    )
    out.append("\n")
    out.append("## Reproducing\n")
    out.append("\n")
    out.append("```sh\n")
    out.append("# Linux / macOS:\n")
    out.append("bash scripts/measure_binary_size.sh\n")
    out.append("\n")
    out.append("# Windows (PowerShell):\n")
    out.append("pwsh scripts/measure_binary_size.ps1\n")
    out.append("```\n")
    out.append("\n")
    out.append(
        "Each invocation rebuilds every combo, overwrites `binary_sizes.csv` "
        "in the repo root, and rewrites this file.\n"
    )

    md_out.write_text("".join(out), encoding="utf-8")
    print(f"wrote {md_out} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
